source ~/zsh/zsh.sh
source ~/zsh/direnv.sh
source ~/zsh/settings.sh
source ~/zsh/path.sh
source ~/zsh/aliases.sh
source ~/zsh/custom_addons.sh
source ~/zsh/fzf.sh
source ~/zsh/scrapy.sh
source ~/zsh/tmux.sh
source ~/zsh/zoxide.sh
